### ISSUE TITLE
Sync is often stuck after not using the phone for a while (with battery saver?)

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-android#1379]
Sent a rageshake. I often notice sync being stuck "forever", at least a few minutes before I either kill riotx or cycle aeroplane mode which makes it work again.

This might happen more often when battery saver is enabled.

**Comment by Bubu** [comment]
To clarify, that is after not using the phone for a few hours, rather than weeks.

**Comment by Bubu** [comment]
I get this without battery saver as well. Send another rageshake, this time while it was stuck.

**Comment by juhovan** [comment]
This often happens on my oneplus 7 pro aswell when display has been off for some time (maybe over an hour or something).
Workaround for me is to exit riotx by swiping it away from recent apps and restarting, which is annoying.

**Comment by danielfrankcom** [comment]
I see the same behavior on a OnePlus 5, I deal with it by killing from the recent apps menu too.

**Comment by kalleeen** [comment]
Having the same issue on my Nokia 7.1, sending a message works but no messages are synced. Fixed by swiping the app from recent apps as well.

**Comment by Bubu** [comment]
This seems to not be happening anymore (for the moment) after switching to Element.

Was there any related work done here?

**Comment by danielfrankcom** [comment]
I am still seeing the same thing even with the new app unfortunately.

**Comment by Bubu** [comment]
I haven't seen this in a looooong time now. So I'm going to close this. If anyone else is experiencing this or similar problems you are probably better off by opening a new image.
