### ISSUE TITLE
Emoji picker: Wrong borders

### ISSUE THREAD

**Issue by kojid0** [vector-im/element-android#2647]
The border of the emoji picker is not correct.
Regular Keyboard
![image](https://user-images.githubusercontent.com/24477557/104090237-be29e500-5275-11eb-9f61-72154ba4e361.png)

Emoji Picker
![image](https://user-images.githubusercontent.com/24477557/104090245-d00b8800-5275-11eb-9ab4-803f33732238.png)

The system buttons are triggered when I select 😟 or 😦.

Removing 2 rows is actually not bad because there are too many emojis displayed anyway (my opinion). I would even remove one column. Quality (users find things fast because they see less options at once) over Quantity (show as many emoji as possible on one screen).

Element version 1.0.12
Android 11
Google Pixel 5

**Comment by kittykat** [comment]
I can't reproduce this so it may have been fixed:

![Screenshot_20220103-111142.png](https://user-images.githubusercontent.com/51663/147924341-db66b844-a336-4011-ab7f-5bee721f043f.png)

**Comment by kojid0** [comment]
> I can't reproduce this so it may have been fixed:

I can still reproduce this on my Google Pixel 5 with Element v1.3.9.
What phone are you using?

**Comment by kittykat** [comment]
@kojid0 Pixel 2 with the Element 1.3.12 - have you tried updating to the latest Element version?

**Comment by kojid0** [comment]
> @kojid0 Pixel 2 with Android 11 and Element 1.3.12 - have you tried updating to the latest Element version?

Using the F-Droid build which is constantly outdated... But I have tried the dbg version (1.3.13-dev) with the very latest commits. The issue is still there. I'm using CalyxOS - therefore I'm not using the stock ROM keyboard (which is SwiftKey, I guess). Could you please install FlorisBoard and try again? If you face the issue after changing to FlorisBoard, then the issue is on the keyboard side, not Element's.

**Comment by bmarty** [comment]
We are using a 3rd party library to show the emoji picker: https://github.com/vanniktech/Emoji. Can you please report the issue there? If you repro the issue with their sample app, it will be appreciated. Thanks!
As a workaround you can scroll a bit to the bottom to click on any emoji without problem, except maybe for emojis of the last row.

**Comment by kojid0** [comment]
> We are using a 3rd party library to show the emoji picker: https://github.com/vanniktech/Emoji. Can you please report the issue there? If you repro the issue with their sample app, it will be appreciated. Thanks! As a workaround you can scroll a bit to the bottom to click on any emoji without problem, except maybe for emojis of the last row.

I'm afraid I don't know how to install their sample app but I will report it over there. 
It's not a top-prio bug as it's just a visual glitch and UX suffers just very little. Therefore I'll close this issue. Thanks for getting in contact anyway! 😊
