### ISSUE TITLE
Emoji autocompleter sometimes leaves search string after replacement

### ISSUE THREAD

**Issue by Bubu** [vector-im/element-android#3449]
#### Describe the bug
When searching for an emoji via `:` autocompletion sometimes it leaves the search text after inserting the emoji. It only happens occasionally but I've found one reliable way to reproduce it, see below:

#### To Reproduce
1. Type `:tada` (it's important to type exactly this)
2. Select the :tada:  emoji from the completer
3. The message composer will now say :tada:`tada`

#### Expected behavior
Tada text is removed

#### Smartphone (please complete the following information):
 - Device: Nexus 5X
 - OS: Android 8.1 (Lineage)

#### Additional context
 - App version and store Schildichat `1.1.7sc33` (I *think* this reproduces with EA as well)
 - Using AOSP keyboard.

**Comment by bmarty** [comment]
I cannot reproduce with Element Android 1.1.8, nor using Schildichat 1.1.7.sc33 on my device running Android 10.

**Comment by Bubu** [comment]
Oh well, thanks for testing. When I got some time I'll try to reproduce this on different phones and see if anything comes up.

**Comment by Bubu** [comment]
And now the same thing doesn't reproduce on my phone anymore.

**Comment by ouchadam** [comment]
I've also been unable to reproduce, this must have been fixed at some point

going to close, feel free to reopen if you experience the issue again!

**Comment by tjaderxyz** [comment]
This still happens to me. It also happens in a more confusing way, that I
just did:

1. type ":a"
2. pick an emoji. The emoji appears and no text remains
3. type "b". "ab" appears in the text box

**Comment by tjaderxyz** [comment]
BTW: I'm on 1.3.7, which is the most recent version on F-Droid.

**Comment by ouchadam** [comment]
:100: thanks for the steps, was able to reproduce 

![emoji-text](https://user-images.githubusercontent.com/1848238/143441150-a52adeb0-63ea-4c7d-a748-7ea6af791111.gif)

**Comment by bmarty** [comment]
Fixed in 1.3.9
