### ISSUE TITLE
Video size not reduce after auto compress before send video

### ISSUE THREAD

**Issue by progserega** [vector-im/element-android#4032]
### Steps to reproduce

1. Capture video by phone ~74 Mb size
2. Try send from gallery
3. See compressing...
4. See, that sending original size of video - ~74 Mb

### What happened?
Element not reduce size of video before send. But show process "compressing".
### What did you expect?
I expect reduce size of video before send to chat.
### What happened?
Video size not reduced.

### Your phone model

Yotaphone 2

### Operating system version

android 6.0.1

### Application version and app store

Element android gplay 1.2.2

### Homeserver

rsprim.ru

### Have you submitted a rageshake?

Yes

**Comment by progserega** [comment]
I upload this video (which try compress and send to matrix) to cloud:
https://yadi.sk/d/hei12MwwZRYHlw

<details>
  <summary>Images of proccess</summary>
  Compress video before sending:
  
![Screenshot_20210917-145031](https://user-images.githubusercontent.com/1297163/133727603-78c7eff6-cfc2-4053-bda4-baf9504f8f8e.png)

After compressing sendding in original size (but must in reduced size):
![Screenshot_20210917-145042](https://user-images.githubusercontent.com/1297163/133727671-77e954bb-2d95-45b3-971c-8c80fafa252f.png)

Error sending, because maby size is big (but on my server set 100 Mb limit for files):
 
![Screenshot_20210917-145147](https://user-images.githubusercontent.com/1297163/133727756-3a240241-0dec-44ea-877f-75077d088e8b.png)

</details>

**Comment by DoM1niC** [comment]
I confirm this problem

**Comment by jtrees** [comment]
Can also confirm. This feature never worked for me.

**Comment by GnaXi** [comment]
I can confirm that this worked for me in the past!
It was a great feature, as it didn't have to actually upload huge files to the Synapse server, but the current version of Element for Android doesn't seem to perform compression at all anymore and just upload the original file?

**Comment by bmarty** [comment]
This is fixed by #4353, in Element 1.3.7

**Comment by Nebukadneza** [comment]
On the 1.3.9 F-Droid build, I have to report that this is still broken for me, and the original description matches the behavior of what I’m seeing.

Thanks for your continued efforts on this great ecosystem though! :tada: :bow:
