### ISSUE TITLE
Opening a room crashes the app.

### ISSUE THREAD

**Issue by Platypuschan** [vector-im/element-android#4788]
### Steps to reproduce

1. Opening a chatroom (all, private rooms and group rooms) by seleting it in the app or open a shortcut from the a chat-notification.
2. Crash.

#### What did you expect?
Viewing the contents of the chat.
#### What happened instead?
The app crashed.

### Your phone model

Xiaomi Redmi 5 Plus

### Operating system version

Android 8.1.0

### Application version and app store

Element 1.3.11

### Homeserver

matrix.home-relay.de

### Will you send logs?

Yes

**Comment by ouchadam** [comment]
this is most likely the emoji crash that was introduce by 1.3.9 and 99% fixed by 1.3.12, does updating to 1.3.12 solve your issue?

**Comment by kavemang** [comment]
> this is most likely the emoji crash that was introduce by 1.3.9 and 99% fixed by 1.3.12, does updating to 1.3.12 solve your issue?

waiting for f-droid update to 1.3.12 to confirm, also having this issue in a certain room

**Comment by hkaancaliskan** [comment]
@ouchadam yep i also have frequent crashes, it started with 1.3.9 and now I'm on 1.3.12, unfortunately not fixed.
Android 11, Galaxy A52, play store version of app
