### ISSUE TITLE
Do not switch selected space by clicking on notification

### ISSUE THREAD

**Issue by witchent** [vector-im/element-android#5180]
#### What would you like to do?
If I click on a notification of a chat it takes me to the correct room, but going back takes me to a space I didn't select before. I would like to disable this behavior such that clicking a notification takes me to the room but still leaves me in the same space I was before.

#### Why would you like to do it?
I have a contact I text frequently, and clicking the notification always take me to a space without all my other important rooms in there. This means I always have to swipe, select my home space, and then select the desired room. 

#### How would you like to achieve it?
I don't know why this behavior is desirable (instead of remembering the last selected space and using it), but if there is a reason for it I would like an option toggle.

### Have you considered any alternatives?

Of course I could add the rooms to the space but this is not what I want to achieve with spaces.

**Comment by wapsi** [comment]
I noticed this too, Element on my Android devices started to act like this recently (after some update, I guess). It's quite annoying.

Previously it didn't switch the space and I would like to have it like that, or at least an option to enable / disable that.

**Comment by lanerussell** [comment]
I've been dealing with the same problem. Are there any updates on getting this resolved? It really breaks the flow of the app having to constantly toggle back to the "Home" space.

**Comment by benparsons** [comment]
I am also experiencing this and dislike it.

**Comment by ASoTNetworks** [comment]
I also dislike this and looks like same as in issue #5476

**Comment by lanerussell** [comment]
I agree; with the current focus on UX and first-time user workflows, I think this ought to be given a high priority.

**Comment by benparsons** [comment]
This behaviour is annoying enough that I have now stopped using personal Spaces to organise rooms. IMO this issue is not high enough priority.

**Comment by witchent** [comment]
Just as a reference, this was probably the pull request which introduced the change
https://github.com/vector-im/element-android/pull/4041

**Comment by bmarty** [comment]
fixed in 1.4.18

**Comment by DooMMasteR** [comment]
This issue has been closed a while ago, bu I am still experiencing random Space switches, then scrolling the list of rooms, just to find me in a spaced where the room I am looking for is not in.

**Comment by TheJJ** [comment]
did you activate that all rooms are shown in the "home" space?

**Comment by TheJJ** [comment]
Settings - Preferences - Spaces - Show all rooms in Home

**Comment by DooMMasteR** [comment]
![Screenshot_20240606-165023](https://github.com/element-hq/element-android/assets/204733/ba5de5ad-fa4e-4249-a921-832524f968fa)
At least my element has no such option

**Comment by TheJJ** [comment]
hahaha mine has:
 ![Screenshot_20240606-165638.png](https://github.com/element-hq/element-android/assets/673543/67043706-2670-479f-b132-6d4804df2495)
