### ISSUE TITLE
Messages are not arriving

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-android#6782]
### Steps to reproduce

1. Be actively chatting with someone in a DM
2. Sometimes see typing notifications for a long time, sometimes not see anything to indicate that the other person is sending a message
3. See the timeline not updating
4. Swipe the app up to close it and then open it again (see green loading screen)
5. Open DM and see messages that were sent minutes ago

#### What did you expect?
I can have a live conversation

#### What happened instead?
I had to keep closing/opening the app to see my messages

### Operating system version

Android 11

### Application version and app store

1.4.31 playstore

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

No

**Comment by kittykat** [comment]
The issue is still persisting

**Comment by witchent** [comment]
I have this issue since a few days, though sadly I don't know when exactly it started.
I don't know if it is related, but the presence updates seem wonky as well.
The messages show fine in Element-Web, but Element Android needs to be force closed to see them.
Using self hosted synapse in my case.

**Comment by sociedadXD** [comment]
I've been having this same issue over the past few days. Both on element android and desktop on fedora.

**Comment by dm-msk** [comment]
Same issue

**Comment by sigma2017** [comment]
Same behavior, no updates on the matrix synapse server side, looks like the issue is on the client side.

**Comment by kylrth** [comment]
Can confirm this is occurring on Android and not on desktop

**Comment by linuxguru96** [comment]
Experiencing same issue on Android

**Comment by dreaddr** [comment]
Experiencing the same issue, messages are not syncing with the homeservers and need a full app refresh to fetch new messages.

**Comment by opusforlife2** [comment]
Should F-Droid users avoid updating from 1.4.25 for now, to be on the safe side?

**Comment by nolimbsdotdev** [comment]
I have the same problem and I think it is also linked to #6823 where you cannot edit your own messages after sending. It's like the client isn't syncing correctly...

**Comment by bmarty** [comment]
I did not find any suspicious logs in the rageshake :/. Will have a second look later.

**Comment by th0mcat** [comment]
Seeing this on Element Android (F-Droid, develop and main builds), but not on desktop.

**Comment by immanuelfodor** [comment]
Very annoying to converse with somebody then accidentally find out later there were other messages that I didn't see 🤦‍♂️😃

**Comment by git-bruh** [comment]
The 'maek read' option in any push notification doesn't work either BTW, not sure if that would be covered by the fix for this

**Comment by dm-msk** [comment]
Still no sync after update.
Ensure SyncThread is started when the app is launched after a Push has been received. (#6884)

**Comment by twouters** [comment]
> Still no sync after update. Ensure SyncThread is started when the app is launched after a Push has been received. (#6884)

I haven't had this issue since updating to 1.4.34, are you sure you're on the correct version? Could also be a different issue or I've been lucky so far.

**Comment by bmarty** [comment]
@dm-msk can you send a rageshake please?

**Comment by dm-msk** [comment]
> rageshake

i've sended rageshake with "ticket 6782" theme

**Comment by bmarty** [comment]
Thanks.
I see lots of logs like this: `/SYNC/SyncTask: Incremental sync request parsing, 0 room(s) 0 toDevice(s)` in your rageshake, so I think there is an issue with your homeserver. You may want to do a clear cache from the app: `Settings/General/Clear cache` to try to fix this.

**Comment by kylrth** [comment]
Yes, this has been fixed now for me since 1.4.34

**Comment by z411** [comment]
Persists for me; I can see in debugging information that the SyncThread is idle. I have to restart the application. Also many times I don't get timely push notifications or voice calls. I'm using MIUI so I wonder if it's killing the thread, although I have it with all restrictions disabled.

**Comment by cpot** [comment]
Still having this issue (or similar) on latest version for Android 1.5.24

Very annoying, please fix it, killing reputation of Element

**Comment by EntityinArray** [comment]
still occurs on android, AMA for info

**Comment by akuckartz** [comment]
Why is this not reopened?

**Comment by bestrocker221** [comment]
The issue still persist for me as well on android, it happens at random times and the fix is always to force close the app and restart it. No notable logs from server side seem to be relevant.

**Comment by andrelaszlo** [comment]
Just putting this here since it's the first search result for me. I've had issues for a long time with a specific chat not loading the latest messages. I get notifications but when I go into the chat room the last message is from last month.

Everything is back to normal after going into settings and clearing the cache!
