### ISSUE TITLE
Return or Paste erase the whole writing before

### ISSUE THREAD

**Issue by tutle** [vector-im/element-android#7562]
### Steps to reproduce

Try to go to next line or paste something from the clipboard.

### Outcome

Erase the whole writing before, happens since release 1.5.4

### Your phone model

Cat S61

### Operating system version

Android 9

### Application version and app store

1.5.4

### Homeserver

matrix.org

### Will you send logs?

Yes

### Are you willing to provide a PR?

Yes

**Comment by conceptionist** [comment]
Another incidence here (after update to 1.5.4)

**Comment by tutle** [comment]
solved in 1.5.7

**Comment by Ezwen** [comment]
A user of my homeserver still encounters this problem with 1.5.7, any idea?

**Comment by tutle** [comment]
But with the 1.5.7 release. it's impossible to answer and quoting a message
